apiVersion: v1
kind: Secret
metadata:
  name: connector-secrets
  namespace: camunda
  labels:
    app.kubernetes.io/part-of: camunda-platform
type: Opaque
stringData:
  ORDER_BASE_AMOUNT: "5000"
  ORDER_DISCOUNT_RATE: "15"
  ORDER_API_KEY: "sk-abc123xyz"
  CUSTOMER_WELCOME_MSG: "Hello and Welcome"
